"""academic_class_subject_terms table

Revision ID: 10ff0c19842f
Revises: b2f7c7fd1a8d
Create Date: 2026-01-21 00:40:41.901665

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10ff0c19842f'
down_revision: Union[str, Sequence[str], None] = 'b2f7c7fd1a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = os.getenv("DB_NAMESPACE") or None
def _fk_target(target: str) -> str:
    if not _SCHEMA:
        return target
    return f"{_SCHEMA}.{target}"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_class_subject_term'),
                       'academic_class_subjects', type_='unique',
                       schema=_SCHEMA)
    op.create_table('academic_class_subject_terms',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('academic_class_subject_id',
                              sa.UUID(), nullable=False),
                    sa.Column('academic_term_id', sa.UUID(), nullable=False),
                    sa.Column('highest_marks', sa.Integer(), nullable=True),
                    sa.Column('average_marks', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['academic_class_subject_id'], [
                        _fk_target('academic_class_subjects.id')], ),
                    sa.ForeignKeyConstraint(['academic_term_id'], [
                                            _fk_target('academic_terms.id')], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('academic_class_subject_id',
                                        'academic_term_id', name='uq_class_subject_term')
                    , schema=_SCHEMA)
    op.drop_constraint(op.f('uq_class_subject_group_position'),
                       'academic_class_subjects', type_='unique',
                       schema=_SCHEMA)
    op.create_unique_constraint('uq_class_subject_group_position', 'academic_class_subjects', [
                                'academic_class_id', 'is_additional', 'position'],
                                schema=_SCHEMA)
    op.create_unique_constraint('uq_class_subject', 'academic_class_subjects', [
                                'academic_class_id', 'subject_id'],
                                schema=_SCHEMA)
    op.drop_constraint(op.f('academic_class_subjects_academic_term_id_fkey'),
                       'academic_class_subjects', type_='foreignkey',
                       schema=_SCHEMA)
    op.drop_column('academic_class_subjects', 'average_marks',
                   schema=_SCHEMA)
    op.drop_column('academic_class_subjects', 'academic_term_id',
                   schema=_SCHEMA)
    op.drop_column('academic_class_subjects', 'highest_marks',
                   schema=_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_class_subjects', sa.Column(
        'highest_marks', sa.INTEGER(), autoincrement=False, nullable=True),
        schema=_SCHEMA)
    op.add_column('academic_class_subjects', sa.Column(
        'academic_term_id', sa.UUID(), autoincrement=False, nullable=False),
        schema=_SCHEMA)
    op.add_column('academic_class_subjects', sa.Column(
        'average_marks', sa.INTEGER(), autoincrement=False, nullable=True),
        schema=_SCHEMA)
    op.create_foreign_key(op.f('academic_class_subjects_academic_term_id_fkey'),
                          'academic_class_subjects', 'academic_terms',
                          ['academic_term_id'], ['id'], schema=_SCHEMA,
                          referent_schema=_SCHEMA)
    op.drop_constraint('uq_class_subject',
                       'academic_class_subjects', type_='unique',
                       schema=_SCHEMA)
    op.drop_constraint('uq_class_subject_group_position',
                       'academic_class_subjects', type_='unique',
                       schema=_SCHEMA)
    op.create_unique_constraint(op.f('uq_class_subject_group_position'), 'academic_class_subjects', [
                                'academic_class_id', 'academic_term_id', 'is_additional', 'position'], postgresql_nulls_not_distinct=False,
                                schema=_SCHEMA)
    op.create_unique_constraint(op.f('uq_class_subject_term'), 'academic_class_subjects', [
                                'academic_class_id', 'subject_id', 'academic_term_id'], postgresql_nulls_not_distinct=False,
                                schema=_SCHEMA)
    op.drop_table('academic_class_subject_terms', schema=_SCHEMA)
    # ### end Alembic commands ###
