"""add_fields_class_verification_status_remark

Revision ID: 6a89ea830441
Revises: 886d0c10abee
Create Date: 2026-02-26 13:28:15.182324

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a89ea830441'
down_revision: Union[str, Sequence[str], None] = '886d0c10abee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = os.getenv("DB_NAMESPACE") or None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gk_competition_students', sa.Column(
        'class_verification_status', sa.String(), nullable=True), schema=_SCHEMA)
    op.add_column('gk_competition_students', sa.Column(
        'remark', sa.String(), nullable=True), schema=_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gk_competition_students', 'remark', schema=_SCHEMA)
    op.drop_column('gk_competition_students',
                   'class_verification_status', schema=_SCHEMA)
    # ### end Alembic commands ###
