"""gk_competition_students_table

Revision ID: 841594fbbd8a
Revises: 10ff0c19842f
Create Date: 2026-02-05 23:40:43.888038

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841594fbbd8a'
down_revision: Union[str, Sequence[str], None] = '10ff0c19842f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = os.getenv("DB_NAMESPACE") or None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gk_competition_students',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('roll_no', sa.String(), nullable=False),
                    sa.Column('father_name', sa.String(), nullable=False),
                    sa.Column('mother_name', sa.String(), nullable=False),
                    sa.Column('class_name', sa.String(), nullable=False),
                    sa.Column('school_name', sa.String(), nullable=False),
                    sa.Column('school_address', sa.String(), nullable=False),
                    sa.Column('aadhaar_no', sa.String(), nullable=False),
                    sa.Column('group', sa.String(), nullable=False),
                    sa.Column('paper_medium', sa.String(), nullable=False),
                    sa.Column('exam_center', sa.String(), nullable=False),
                    sa.Column('contact_no', sa.String(), nullable=False),
                    sa.Column('marks', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('aadhaar_no', name='uq_gk_competition_students_aadhaar_no'),
                    sa.UniqueConstraint('roll_no', name='uq_gk_competition_students_roll_no'),
                    schema=_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gk_competition_students', schema=_SCHEMA)
    # ### end Alembic commands ###
