"""add_admit_card_active_to_app_settings

Revision ID: 886d0c10abee
Revises: b86f78d6f959
Create Date: 2026-02-16 18:47:48.166107

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '886d0c10abee'
down_revision: Union[str, Sequence[str], None] = 'b86f78d6f959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = os.getenv("DB_NAMESPACE") or None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column(
        'gk_competition_admit_card_active',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("false"),
    ), schema=_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'app_settings', 'gk_competition_admit_card_active', schema=_SCHEMA)
    # ### end Alembic commands ###
