"""update_app_settings

Revision ID: b86f78d6f959
Revises: 841594fbbd8a
Create Date: 2026-02-06 20:59:04.916849

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b86f78d6f959'
down_revision: Union[str, Sequence[str], None] = '841594fbbd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = os.getenv("DB_NAMESPACE") or None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column(
        'gk_competition_result_active', sa.Boolean(), nullable=False), schema=_SCHEMA)
    op.drop_column('app_settings', 'test_field', schema=_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column(
        'test_field', sa.VARCHAR(), autoincrement=False, nullable=False), schema=_SCHEMA)
    op.drop_column('app_settings', 'gk_competition_result_active')
    # ### end Alembic commands ###
