"""add all models

Revision ID: bd73b3d9a8e6
Revises: 
Create Date: 2026-01-15 19:41:22.912024

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd73b3d9a8e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='academic_sessions_year_key')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('test_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('registration_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_registration_no'), 'students', ['registration_no'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('academic_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('academic_session_id', sa.UUID(), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_session_id', 'grade', 'section', name='uq_academic_classes_session_grade_section')
    )
    op.create_table('academic_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('academic_session_id', sa.UUID(), nullable=False),
    sa.Column('term_type', sa.Enum('ANNUAL', 'HALF_YEARLY', 'QUARTERLY', name='academictermtype'), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('exam_result_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_session_id', 'term_type', name='academic_terms_academic_session_id_term_type_key')
    )
    op.create_table('academic_class_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('academic_class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('highest_marks', sa.Integer(), nullable=True),
    sa.Column('average_marks', sa.Integer(), nullable=True),
    sa.Column('is_additional', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_class_id', 'academic_term_id', 'is_additional', 'position', name='uq_class_subject_group_position'),
    sa.UniqueConstraint('academic_class_id', 'subject_id', 'academic_term_id', name='uq_class_subject_term')
    )
    op.create_table('date_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('academic_class_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_class_id', 'academic_term_id', name='uq_date_sheets_class_term')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_session_id', sa.UUID(), nullable=False),
    sa.Column('academic_class_id', sa.UUID(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_session_id', name='uq_enrollment_session')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('default_academic_session_id', sa.UUID(), nullable=True),
    sa.Column('default_academic_term_id', sa.UUID(), nullable=True),
    sa.Column('default_academic_class_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['default_academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['default_academic_session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['default_academic_term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('date_sheet_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('date_sheet_id', sa.UUID(), nullable=False),
    sa.Column('academic_class_subject_id', sa.UUID(), nullable=False),
    sa.Column('paper_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['academic_class_subject_id'], ['academic_class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['date_sheet_id'], ['date_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('work_education_grade', sa.Enum('A', 'B', 'C', 'D', 'E', name='reportcardgrade'), nullable=True),
    sa.Column('art_education_grade', sa.Enum('A', 'B', 'C', 'D', 'E', name='reportcardgrade'), nullable=True),
    sa.Column('physical_education_grade', sa.Enum('A', 'B', 'C', 'D', 'E', name='reportcardgrade'), nullable=True),
    sa.Column('behaviour_grade', sa.Enum('A', 'B', 'C', 'D', 'E', name='reportcardgrade'), nullable=True),
    sa.Column('attendance_present', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('PROMOTED', 'PASSED', 'NEED_IMPROVEMENT', 'RESULT_WITHHELD', name='reportcardresult'), nullable=True),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'academic_term_id', name='uq_report_card_enrollment_term')
    )
    op.create_table('report_card_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_card_id', sa.UUID(), nullable=False),
    sa.Column('academic_class_subject_id', sa.UUID(), nullable=False),
    sa.Column('mid_term', sa.Integer(), nullable=True),
    sa.Column('notebook', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.Integer(), nullable=True),
    sa.Column('class_test', sa.Integer(), nullable=True),
    sa.Column('final_term', sa.Integer(), nullable=True),
    sa.Column('final_marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_class_subject_id'], ['academic_class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_card_id'], ['report_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_card_id', 'academic_class_subject_id', name='uq_report_card_subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_card_subjects')
    op.drop_table('report_cards')
    op.drop_table('date_sheet_subjects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('enrollments')
    op.drop_table('date_sheets')
    op.drop_table('academic_class_subjects')
    op.drop_table('academic_terms')
    op.drop_table('academic_classes')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_students_registration_no'), table_name='students')
    op.drop_table('students')
    op.drop_table('app_settings')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###
